apiVersion: v1
kind: Pod
metadata:
  name: kong-pre-configure
spec:
  restartPolicy: OnFailure
  containers:
  - name: kong-migrate
    image: kong:0.13.0
    env:
    - name: KONG_DATABASE
      value: postgres
    - name: KONG_PG_HOST
      value: kong-postgres
    - name: KONG_PG_DATABASE
      value: kong
    - name: KONG_PG_USER
      value: kong
    - name: KONG_PG_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kong-postgres
          key: postgres-password
    command: [ "/bin/sh", "-c", "KONG_NGINX_DAEMON='off' kong migrations up" ]
