defaultRules.rules.kubeApiserver: false
defaultRules.rules.kubeScheduler: false
defaultRules.rules.etcd: false

prometheus:
  prometheusSpec:
    ruleNamespaceSelector:
      any: true
    serviceMonitorNamespaceSelector:
      any: true
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      limits:
        cpu: 500m
        memory: 3Gi
      requests:
        cpu: 500m
        memory: 3Gi
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
alertmanager:
  config:
    receivers:
      - name: pagerduty
        pagerduty_configs:
        - service_key: <TO SET DURING HELM INSTALL>
    route:
      group_by:
      - job
      group_wait: 30s
      group_interval: 5m
      receiver: pagerduty
      repeat_interval: 3h
      routes:
      - match:
          alertname: Watchdog
        receiver: pagerduty

grafana:
  enabled: false
