paths:
  outputDir: .
  terraformTemplatePath: templates/networking.tf.template
  kopsTemplatePath: templates/kops.yaml.template
  sshPublicKeyPath: /path/to/ssh/key/id_rsa.pub
  tillerPermissions: tiller-permissions.yaml
clusterConfig:
  FullyQualifiedName: mycluster.mycompany.com
  ShortName: mycluster
  ConfigBaseURL: s3://mycompany-kops-config
  AWSRegion: eu-west-2
  AWSAZ1: a
  MasterMachineType: t2.small
  MasterMinNumber: 2
  MasterMaxNumber: 2
  NodeMachineType: m4.large
  NodeMaxNumber: 3
  NodeMinNumber: 3
  BastionMachineType: t2.micro
  BastionMaxNumber: 1
  BastionMinNumber: 1
  KubernetesVersion: "1.7.1"
chartRepos:
  - name: sprinthive-charts
    url: https://s3.eu-west-2.amazonaws.com/sprinthive-charts
charts:
  - name: sprinthive-charts/kong-cassandra
    namespace: infra
    release: gwdb
  - name: sprinthive-charts/routed-service-controller
    namespace: infra
    release: inggw
    overrides: kong.ProxyService.Type=LoadBalancer,kong.ProxyService.HttpEnabled=false
