apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://promop-prometheus-operator-prometheus:9090/
      access: proxy
      isDefault: true
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: grafana
    grafana_datasource: "1"
  name: datasource-prometheus
