apiVersion: v1
data:
  ESLogs.json: |-
    {
      "orgId": 1,
      "name": "ES Logs",
      "type": "elasticsearch",
      "typeLogoUrl": "public/app/plugins/datasource/elasticsearch/img/elasticsearch.svg",
      "access": "proxy",
      "url": "http://elasticsearch.infra:9200",
      "password": "",
      "user": "",
      "database": "[logstash-]YYYY.MM.DD",
      "basicAuth": false,
      "isDefault": false,
      "jsonData": {
        "esVersion": 5,
        "interval": "Daily",
        "timeField": "@fb_timestamp"
      }
    }
  Prometheus.json: |
    {
      "orgId": 1,
      "name": "Prometheus",
      "type": "prometheus",
      "typeLogoUrl": "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg",
      "access": "proxy",
      "url": "http://metricdb-prometheus-server.infra",
      "password": "",
      "user": "",
      "database": "",
      "basicAuth": false,
      "isDefault": false,
      "jsonData": {}
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grafana-datasources
